### ISSUE TITLE
Keep getting an error when attempting to login

### ISSUE THREAD

**Issue by loneshaman** [andyh2/davislib#1]
Traceback (most recent call last):
  File "examples/graduate.py", line 204, in <module>
    main()
  File "examples/graduate.py", line 198, in main
    add_term_credit(area_credit, flagged, sw, reg, term)
  File "examples/graduate.py", line 172, in add_term_credit
    cat_conflicts = category_conflicts(course)
  File "examples/graduate.py", line 56, in category_conflicts
    for area in course.ge_areas:
AttributeError: 'Course' object has no attribute 'ge_areas'

Looked through the files and Course definitely has the ge_area attribute. Is there a connection I'm missing?

(Testing this on the UC Davis CSIF)

**Comment by andyh2** [comment]
I just fresh cloned the repo on CSIF and the example script works fine. Is your local repo up to date? Try a `git pull`. 
Even if a course doesn't have any GE areas listed online, the attribute should still resolve to an empty list.

**Comment by loneshaman** [comment]
Looks like pulling fixed that issue, but a new traceback issue popped up. I'll post the text here, but let me know if you want me to make it a separate issue

Traceback (most recent call last):
  File "examples/graduate.py", line 204, in <module>
    main()
  File "examples/graduate.py", line 198, in main
    add_term_credit(area_credit, flagged, sw, reg, term)
  File "examples/graduate.py", line 171, in add_term_credit
    course = reg.course_detail(term, crn)
  File "/home/spinnipa/.local/lib/python3.3/site-packages/davislib-0.1-py3.3.egg/davislib/registrar.py", line 44, in course_detail
    return Course(**course_attrs)
  File "/home/spinnipa/.local/lib/python3.3/site-packages/davislib-0.1-py3.3.egg/davislib/models.py", line 139, in **init**
    self.available_seats = attrs['available_seats']
KeyError: 'available_seats'

**Comment by andyh2** [comment]
Let's make a new issue for this one.
