### ISSUE TITLE
Available Seats not defined

### ISSUE THREAD

**Issue by andyh2** [andyh2/davislib#2]
Traceback (most recent call last):
File "examples/graduate.py", line 204, in 
main()
File "examples/graduate.py", line 198, in main
add_term_credit(area_credit, flagged, sw, reg, term)
File "examples/graduate.py", line 171, in add_term_credit
course = reg.course_detail(term, crn)
File "/home/spinnipa/.local/lib/python3.3/site-packages/davislib-0.1-py3.3.egg/davislib/registrar.py", line 44, in course_detail
return Course(**course_attrs)
File "/home/spinnipa/.local/lib/python3.3/site-packages/davislib-0.1-py3.3.egg/davislib/models.py", line 139, in init
self.available_seats = attrs['available_seats']
KeyError: 'available_seats'

Looks like available seats wasn't listed for a course in the schedule.

**Comment by andyh2** [comment]
I incorrectly assumed that the registrar lists available seats and maximum enrollment for previous-year courses.

**Comment by loneshaman** [comment]
Traceback (most recent call last):
  File "examples/graduate.py", line 202, in <module>
    main()
  File "examples/graduate.py", line 196, in main
    add_term_credit(area_credit, flagged, sw, reg, term)
  File "examples/graduate.py", line 169, in add_term_credit
    course = reg.course_detail(term, crn)
  File "/home/spinnipa/.local/lib/python3.3/site-packages/davislib-0.1-py3.3.egg/davislib/registrar.py", line 44, in course_detail
    return Course(**course_attrs)
  File "/home/spinnipa/.local/lib/python3.3/site-packages/davislib-0.1-py3.3.egg/davislib/models.py", line 139, in **init**
    self.available_seats = attrs['available_seats']
KeyError: 'available_seats'
[spinnipa@pc44 davislib]$ git pull
Already up-to-date.

Still getting an error, and I just pulled.

**Comment by andyh2** [comment]
@loneshaman did you re-run `python3 setup.py install --user` in order to update your local package installation?

**Comment by loneshaman** [comment]
I didn't. Now that I did, it works perfectly. Thanks!
